const gulp = require('gulp');

gulp.task('scripts:build', function(done) {
	const webpack = require('webpack-stream');

	return gulp.src('assets/scripts/main.js')
		.pipe(webpack(require('./webpack.config.js')))
		.pipe(gulp.dest('static/scripts'));
});

gulp.task('scripts:minify', function(done) {
	const uglify = require('gulp-uglify');

	return gulp.src('public/scripts/*.js')
		.pipe(uglify())
		.pipe(gulp.dest('public/scripts'));
});

gulp.task('styles:build', function() {
	const path = require('path');
	const sass = require('gulp-sass');

	return gulp.src('assets/styles/screen.scss')
		.pipe(sass({
			paths: [
				path.join(__dirname, 'scss', 'includes')
			]
		}))
		.pipe(gulp.dest('static/styles'));
})

gulp.task('styles:minify', function() {
	const cssnano = require('gulp-cssnano');
	const purifycss = require('gulp-purifycss');

	return gulp.src('public/styles/*.css')
		.pipe(purifycss([
			'public/**/*.html',
			'static/scripts/*.js'
		]))
		.pipe(cssnano())
		.pipe(gulp.dest('public/styles'));
})

gulp.task('images:copy', function() {
	return gulp.src('assets/images/**/*').pipe(gulp.dest('static/images'));
})

gulp.task('images:svg:minify', function() {
	const svgmin = require('gulp-svgmin');

	return gulp.src('public/images/**/*.svg')
		.pipe(svgmin())
		.pipe(gulp.dest('public/images'));
})

gulp.task('fonts:copy', function() {
	return gulp.src(['assets/fonts/*', 'node_modules/font-awesome/fonts/*']).pipe(gulp.dest('static/fonts'));
})

gulp.task('html:minify', function() {
	const htmlmin = require('gulp-htmlmin');

	return gulp.src('public/**/*.html')
		.pipe(htmlmin({
			collapseBooleanAttributes: true,
			collapseWhitespace: true,
			conservativeCollapse: true,
			decodeEntities: true,
			html5: true,
			includeAutoGeneratedTags: false,
			minifyJS: true,
			removeComments: true,
			removeRedundantAttributes: true
		}))
		.pipe(gulp.dest('public'));
})

gulp.task('fingerprint', function() {
	const cacheBust = require('gulp-cache-bust');

	return gulp.src(['public/**/*.html'])
		.pipe(cacheBust())
		.pipe(gulp.dest('public'));
})

gulp.task('default', [
	'scripts:build',
	'styles:build',
	'images:copy',
	'fonts:copy'
]);

gulp.task('optimize', [
	'scripts:minify',
	'styles:minify',
	'html:minify',
	'images:svg:minify'
]);
